version: '3'
services:
  cadence:
    image: ubercadence/server:master-auto-setup
    container_name: cadence
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
      - "7833:7833"
    environment:
      - "DB=postgres"
      - "DB_PORT=15432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PWD=postgres"
      - "POSTGRES_SEEDS=172.17.0.1"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
  cadence-web:
    image: ubercadence/web:latest
    container_name: cadence-web
    restart: unless-stopped
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
