version: '2'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    hostname: keycloak
    restart: unless-stopped
    ports: 
     - "8888:8080"
     - "8787:8787"
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
     - KC_DB=postgres  
     - KC_DB_URL=jdbc:postgresql://172.17.0.1/keycloak
     - KC_DB_USERNAME=postgres
     - KC_DB_PASSWORD=postgres
     - KC_DB_DATASBASE=keycloak
    command:
      - start-dev
