version: '2'
services:
 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq
  hostname: rabbitmq
  restart: unless-stopped
  ports:
   - "5672:5672"
   - "15672:15672"
   - "61613:61613"
  volumes:
   - ~/docker/rabbitmq_data:/var/lib/rabbitmq
  environment:
   - RABBITMQ_ERLANG_COOKIE=cluster_cookie
   - RABBITMQ_DEFAULT_USER=admin
   - RABBITMQ_DEFAULT_PASS=admin
 rabbitmq-setup:
  build: .
  container_name: rabbitmq-setup
  image: rabbitmq:3-management
  restart: "no"
  command: sh -c "rabbitmq-plugins enable rabbitmq_web_stomp"
  volumes:
   - ~/docker/rabbitmq_data:/var/lib/rabbitmq
  depends_on:
   - rabbitmq


