version: '2'

services:
 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq
  hostname: rabbitmq
  restart: unless-stopped
  ports:
   - "5672:5672"
   - "15672:15672"
   - "61613:61613"
  volumes:
   - ./rabbitmq_data:/var/lib/rabbitmq
  environment:
   - RABBITMQ_ERLANG_COOKIE=cluster_cookie
   - RABBITMQ_DEFAULT_USER=admin
   - RABBITMQ_DEFAULT_PASS=admin
