---
apiVersion: v1
kind: Service
metadata:
  name: paygate
  labels:
    app: paygate
spec:
  type: NodePort
  selector:
    app: paygate
  ports:
    - protocol: TCP
      port: 1125
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paygate
spec:
  selector:
    matchLabels:
      app: paygate
  replicas: 1
  template:
    metadata:
      labels:
        app: paygate
    spec:
      containers:
        - name: paygate
          image: tiktzuki/paygate:latest
          ports:
            - containerPort: 1125
          livenessProbe:
            httpGet:
              path: /
              port: 1125
            initialDelaySeconds: 30
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: paygate-config