---
apiVersion: v1
kind: Service
metadata:
  name: klb-pay
  labels:
    app: klb-pay
spec:
  type: NodePort
  selector:
    app: klb-pay
  ports:
    - protocol: TCP
      port: 1124
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klb-pay
spec:
  selector:
    matchLabels:
      app: klb-pay
  replicas: 1
  template:
    metadata:
      labels:
        app: klb-pay
    spec:
      containers:
        - name: klb-pay
          image: tiktzuki/klb-pay:latest
          ports:
            - containerPort: 1124
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 1124
            initialDelaySeconds: 30
            timeoutSeconds: 1
          env:
            - name: VPS
              value: "14.225.205.235"
            - name: DATABASE_URL
              value: "jdbc:mysql://${VPS}:23306/klb-pay"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "P@ssword789"
            - name: MONGO_URI
              value: "mongodb://guest:P%40ssword789@${VPS}:27017/guest"
            - name: REDIS_HOST
              value: ${VPS}
            - name: REDIS_PORT
              value: "26379"
            - name: REDIS_PASSWORD
              value: "P@ssword789"
            - name: CADENCE_HOST
              value: ${VPS}
            - name: CADENCE_PORT
              value: "37933"
            - name: CADENCE_DOMAIN
              value: "klb-pay-dev"
            - name: CADENCE_WF_ACT_INTERVAL
              value: "30s"
            - name: CADENCE_WF_ACT_START_TO_CLOSE
              value: "40s"
            - name: MAX_TIMESTAMP_DIFF_MS
              value: "180000"
            - name: MAXIMUM_POOL_SIZE
              value: "24"
