version: "2"
services:
  elk:
    image: tiktzuki/elk:latest
    container_name: elk
    restart: unless-stopped
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./elk_data:/var/lib/elasticsearch
