version: "2"

services:
  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elastic
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "es-data:/usr/share/elasticsearch/data"
    networks:
      - logging
  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - logging
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:8.6.1
    container_name: logstash
    command: logstash -f /config/
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./logstash/config:/config
    networks:
      - logging
    depends_on:
      - elasticsearch

volumes:
  es-data:
    driver: local

networks:
  logging:
    driver: bridge
