version: "3.1"
services:
  postgres:
    # *-----------------------------*
    # To connect to the DB:
    #   docker exec -it postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
    # *-----------------------------*
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      PGUSER: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssword789
      POSTGRES_DB: root
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    network_mode: bridge
