version: "3.1"
services:
  postgres:
    # *-----------------------------*
    # To connect to the DB:
    #   docker exec -it postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
    # *-----------------------------*
    image: postgres:12
    container_name: postgres-12
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      PGUSER: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssword789
      POSTGRES_DB: root