version: "3.5"
services:
  temporal:
    image: temporalio/auto-setup:1.20.0
    container_name: temporal
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PWD=P@ssword789
      - POSTGRES_SEEDS=172.17.0.1
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - temporal-network
  temporal-admin-tools:
    image: temporalio/admin-tools:1.20.0
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    networks:
      - temporal-network
  temporal-ui:
    image: temporalio/ui:2.10.3
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - 1090:8080
    networks:
      - temporal-network
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
